name: Publish Docker image

on:
  release:
    types: 
    - published

jobs:
  push_to_registry:
    name: Push module to npm
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: build
        run: npm run build

      - name: release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
