name: release latest

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
jobs:
  push_to_npm:
    name: Push module to npm
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kkuwa'

      - name: build
        run: npm run build

      - name: Check is latest tag
        run: |
          npx semver -r ">$GIT_TAG" $(git tag) > /dev/null
          IS_LATEST_RELEASE=$? >> $GITHUB_ENV
        env:
          GIT_TAG: "${{ github.event.release.tag_name }}"

      - name: release latest
        if: "env.IS_LATEST_RELEASE == '1'"
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: release stable
        if: "env.IS_LATEST_RELEASE == '0'"
        run: npm publish --tag ${{ github.ref_name }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  push_to_github:
    name: Release artifacts to github
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kkuwa'

      - name: build
        run: npm run build

      - name: bundle
        env:
          WORK_DIR: ${{ github.workspace }}
        run: |
          tar czf - lib > $WORK_DIR/bundle.tar.gz

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bundle.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ github.event.release.tag_name }}"
          allowUpdates: true

  push_to_dockerhub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check is latest tag
        run: |
          npx semver -r ">$GIT_TAG" $(git tag) > /dev/null
          IS_LATEST_RELEASE=$? >> $GITHUB_ENV
        env:
          GIT_TAG: "${{ github.event.release.tag_name }}"

      - name: Extract metadata (tags, labels) for Docker for latest
        if: "env.IS_LATEST_RELEASE == '1'"
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: kkuwa/my-automatebuild-test
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push Docker image for latest
        if: "env.IS_LATEST_RELEASE == '1'"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Extract metadata (tags, labels) for Docker for stable
        if: "env.IS_LATEST_RELEASE == '0'"
        id: metastable
        uses: docker/metadata-action@v3
        with:
          images: kkuwa/my-automatebuild-test
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=${{ github.ref_name }}

      - name: Build and push Docker image for stable
        if: "env.IS_LATEST_RELEASE == '0'"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.metastable.outputs.tags }}